version: "3.9"

services:
  backend:
    build: ./backend/ecommerce-core
    container_name: atelie-backend
    ports:
      - "${APP_PORT}:8080"  # Pega do .env
    depends_on:
      - db
    environment:
      # Passando as variáveis do .env para dentro do Java
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      # Correção do Flyway que fizemos antes
      - SPRING_FLYWAY_VALIDATE_ON_MIGRATE=false
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
    networks:
      - atelie-network
    restart: always

  db:
    image: postgres:15-alpine
    container_name: atelie-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - atelie-network
    restart: always

volumes:
  postgres_data:

networks:
  atelie-network:
    driver: bridge