version: "3.9"

services:
  backend:
    image: atelie-backend
    container_name: atelie-backend
    build:
      context: ./backend/ecommerce-core
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Sobrescreve as configs do application.properties para rodar no Docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ecommerce_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    restart: unless-stopped
    volumes:
       - ./uploads:/app/uploads

  db:
    image: postgres:15-alpine
    container_name: atelie-db
    ports:
      - "5432:5432" # Expõe para você acessar via DBeaver/PgAdmin se quiser
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: