services:
  # --- INFRAESTRUTURA (BANCO) ---
  db:
    image: postgres:16-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_DB: ${DB_NAME:-ecommerce_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-local_dev_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- BACKEND (API) ---
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ecommerce-api:latest
    container_name: ecommerce_api
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME:-ecommerce_db}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-local_dev_password}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      # A LINHA QUE FALTAVA:
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads

  # --- FRONTEND (DASHBOARD ADMIN) ---
  dashboard:
    build:
      context: ./dashboard-admin
      dockerfile: Dockerfile
    image: ecommerce-dashboard:latest
    container_name: ecommerce_dashboard
    ports:
      - "3000:80"
    depends_on:
      - api

  # --- FRONTEND (LOJA CLIENTE) ---
  store:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ecommerce-store:latest
    container_name: ecommerce_store
    ports:
      - "3001:3000"
    depends_on:
      - api

volumes:
  postgres_data:
