services:
  # 1. Banco de Dados (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_dev_password
    ports:
      - "5432:5432" # Expõe porta para você acessar via DBeaver/PgAdmin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Aplicação Backend (Spring Boot)
  app:
    build: .
    container_name: ecommerce_api
    ports:
      - "8080:8080" # API acessível em localhost:8080
    environment:
      # Conexão com o Banco (Note o host 'db')
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommerce_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: local_dev_password
      
      # Configurações de Segurança e JWT (Valores de Dev)
      JWT_SECRET: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      JWT_EXPIRATION_MS: 86400000
      
      # Webhooks e Integrações (Vazios inicialmente)
      WEBHOOK_SECRET: dev_secret
      
      # Permite o Frontend acessar (CORS)
      CORS_ALLOWED_ORIGINS: "*" 
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads # Persiste uploads na sua máquina

volumes:
  postgres_data:
