services:
  db:
    image: postgres:16-alpine
    container_name: ecommerce_db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_dev_password
    ports:
      - "5433:5432" # Host:5433 -> Container:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ecommerce_api
    ports:
      - "8081:8080" # <--- MUDANÃ‡A AQUI: Host:8081 -> Container:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommerce_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: local_dev_password
      JWT_SECRET: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      JWT_EXPIRATION_MS: 86400000
      WEBHOOK_SECRET: dev_secret
      CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
